### ISSUE TITLE
Add ability to do auto-walk pathing from sign to sign, disable teleportation.

### ISSUE THREAD

**Issue by VinterNacht** [RasaNovum/Via_Romana#5]
I got really excited about this mod before I realized the roads were teleportation rather than "click sign, start auto-walking the path" implementation. I totally understand if this is outside the scope of your mod, but is there any way we could get a "follow from sign to sign" option?  If not, still a very cool mod, good on you.

If you would consider this, perhaps the type of block the path is made from can provide a configurable movement boost?

**Comment by xameryn** [comment]
Currently the system in use doesn't record the actual path, it only checks two position at a time to guarantee the path is made using infrastructure blocks, so that would make the auto-walk/path-following impossible. That said I'm looking into changing the path-check system so that it would hold all path data so when/if I make that change I'll re-open this issue as it would be possible.

**Comment by VinterNacht** [comment]
That's amazing. Admittedly, I had figured you'd path from one sign to the next on a designated path. Or at least to the next point where the player stood when they charted the course to the next sign.  I hope this becomes possible! Thank you for your attention.

**Comment by VinterNacht** [comment]
Any update on progressing this implementation?

**Comment by xameryn** [comment]
Not at the moment, many more fish to fry currently but definitely something I'd add if I refactored how the path data is saved.
